use_frameworks!

platform :ios, '15.0'

target 'KiwiPublicPod_Example' do
  pod 'KiwiPublicPod', :path => '../'
#  pod 'KiwiPublicPod', '~> 0.1.2'

  # 开发环境专用
#  pod 'SwiftGen', '~> 6.6.3', :configurations => ['Debug']
  
  # 数据转模型
#  pod 'HandyJSON', '5.0.0'
  
end
